Repository linebender/piet, pull requests merged in 2024-10, with the labels that each got.

#579 Clarify how to run examples.
  README.md
Labels: maintenance

#578 Add a robust way to temporarily end Direct2D drawing.
  piet-common/src/direct2d_back.rs
  piet-direct2d/src/d2d.rs
Labels: piet-direct2d

#583 Update more deps.
  piet-cairo/Cargo.toml
  piet-coregraphics/Cargo.toml
  piet-direct2d/Cargo.toml
  piet-svg/Cargo.toml
  piet/Cargo.toml
Labels: maintenance

#582 Prepare for releasing v0.7.0.
  piet-cairo/Cargo.toml
  piet-common/Cargo.toml
  piet-coregraphics/Cargo.toml
  piet-direct2d/Cargo.toml
  piet-svg/Cargo.toml
  piet-web/Cargo.toml
  piet/Cargo.toml
Labels: maintenance

#586 Enable the console feature for web-sys.
  piet-web/Cargo.toml
Labels: piet-web

#587 Update readme badges and `main` branch references.
  CONTRIBUTING.md
  README.md
Labels: maintenance
